#!/usr/bin/php -q
<?php
include("bin2latlon.php");

$url = "http://data.cityofnewyork.us/resource/2jy7-cddj.json";
$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $url); 
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1');            
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE); 
$response = json_decode(curl_exec($ch));
curl_close($ch); 

$data = $response;

foreach($data as $_row) {
	$row = (array)$_row;
	foreach($row as $label=>$value) {
		$row[str_replace("_", "", $label)] = trim($value);
	}

	process_row($row);
}



function process_row($row) {
	if($row['permitsubtype'] != "SH")
		return;

	$id = $row['job'] . "-" . $row['jobdoc'] . "-" . $row['permittype'] . "-" . $row['permitsubtype'] . "-" . $row['permitsequence'];


	$url = "http://jeffmaki.cartodb.com/api/v2/sql?q=" . urlencode("SELECT COUNT(*) FROM sheds WHERE permit_id='" . $id . "'");
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, $url); 
	curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1');            
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE); 
	$response = json_decode(curl_exec($ch));
	curl_close($ch); 

	if($response->rows[0]->count != 0) {
		echo "Permit $id already in DB. Skipping...\n";
		return;
	}


	$latlong_parts = addr2latlon($row['house'], $row['streetname'], $row['borough']);
//	$latlong_parts = bin2latlon($row['PtBin']);
	$lat = $latlong_parts[1];
	$lon = $latlong_parts[0];

	$query = "INSERT INTO sheds(permit_id, issue_date, expiration_date, bin, the_geom, house_number, street, borough) VALUES (";
	$query .= "'" . $id . "',";
	$query .= "'" . $row['issuancedate'] . "',";
	$query .= "'" . $row['expirationdate'] . "',";
	$query .= "'" . $row['bin'] . "',";
	$query .= "GeomFromText('POINT(" . $lon . " " . $lat . ")', 4326),";
	$query .= "'" . $row['house'] . "',";
	$query .= "'" . $row['streetname'] . "',";
	$query .= "'" . $row['borough'] . "'";
	$query .= ")";

	$url = "http://jeffmaki.cartodb.com/api/v2/sql?q=" . urlencode($query) . "&api_key=";
	$ch = curl_init(); 
	curl_setopt($ch, CURLOPT_URL, $url); 
	curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1');            
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE); 
	$response = curl_exec($ch); 
	curl_close($ch); 
}

